project_id = "uavzziigfnqpfdkczbdo"

[functions.gmail-sync]
verify_jwt = false

[functions.gmail-send]
verify_jwt = false

[functions.ringcentral-sync]
verify_jwt = false

[functions.ai-agent]
verify_jwt = false

[functions.google-oauth]
verify_jwt = false